# -*- coding: utf-8 -*-
"""analisi_spese_mensili.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wnkZwT9KnAQbvnG3VeNf8RB8VrL-nl7Q
"""

!pip install openpyxl

import openpyxl
import pandas
from openpyxl.styles import PatternFill
from openpyxl.chart import PieChart, BarChart, Reference
from openpyxl.chart.series import DataPoint
from openpyxl.chart.label import DataLabelList

#caricare file excel
#file_path = 'spese_giugno_2026.xlsx'
#excel = openpyxl.load_workbook(file_path)
#estratto_conto = excel.active

import glob

file_disponibili = glob.glob("*.xlsx")
for i, nome in enumerate(file_disponibili):
    print(i, "-", nome)

# chiedo all'utente quale file analizzare
scelta = int(input("Digitare il numero del file da analizzare: "))

# recupero il nome corrispondente e lo carico
file_path = file_disponibili[scelta]
excel = openpyxl.load_workbook(file_path)
estratto_conto = excel.active

print(f"Sto analizzando: {file_path}")


#crea foglio analisi se non presente
if 'Foglio_analisi' not in excel.sheetnames:
  foglio_analisi = excel.create_sheet(title='Foglio_analisi')
elif 'Foglio_analisi' in excel.sheetnames:
  foglio_analisi = excel['Foglio_analisi']
  foglio_analisi.delete_cols(1,1000)


#Formattazione del foglio
foglio_analisi.sheet_properties.tabColor = '008000'
foglio_analisi.sheet_view.showGridLines = False

"""Prima funzione che calcola entrate ed uscite: somma tutte le voci con importo negativo come uscite (compresi gli investimenti perchè in genere vengono passati ad un conto diverso) e poi viene effettuata una somma per categoria di uscite"""

entrate = 0
uscite = 0
investimenti = 0

for riga in estratto_conto.iter_rows(min_row=2, values_only=True):
    importo = riga[1]
    if importo > 0:
        entrate += importo
    elif importo < 0:
      if riga[2] == 'Liquidità investita':
        investimenti += importo
      else:
        uscite += importo

foglio_analisi['A1'] = "Entrate totali"
foglio_analisi['B1'] = entrate

foglio_analisi['A2'] = "Uscite totali"
foglio_analisi['B2'] = uscite * (-1)

foglio_analisi['A3'] = "Investimenti"
foglio_analisi['B3'] = investimenti * (-1)

foglio_analisi['A4'] = "Saldo";
foglio_analisi['B4'] = entrate + uscite + investimenti


# Somme parziali per categoria

spese_categoria = {}
for riga in estratto_conto.iter_rows(min_row=2, values_only=True):
    importo = riga[1]
    categoria = riga[2]
    if importo < 0:
        spesa = abs(importo)
        if categoria in spese_categoria:
            spese_categoria[categoria] += spesa
        else:
            spese_categoria[categoria] = spesa

foglio_analisi['A7'] = "Categoria"; foglio_analisi['B7'] = "Spesa"
riga_corrente = 8
for categoria, totale in spese_categoria.items():
    foglio_analisi[f'A{riga_corrente}'] = categoria
    foglio_analisi[f'B{riga_corrente}'] = totale
    riga_corrente += 1

ultima_riga = 7 + len(spese_categoria)

# Grafico a torta

dati_torta = Reference(foglio_analisi, min_col=2, min_row=2, max_row=4)
cat_torta  = Reference(foglio_analisi, min_col=1, min_row=2, max_row=4)

torta = PieChart()
torta.title = "Ripartizione spese"
torta.add_data(dati_torta)
torta.set_categories(cat_torta)
torta.dataLabels = DataLabelList()
torta.dataLabels.showPercent = True
foglio_analisi.add_chart(torta, "D5")

#Grafico a barre verticali
dati_barre = Reference(foglio_analisi, min_col=2, min_row=7, max_row=ultima_riga)
cat_barre  = Reference(foglio_analisi, min_col=1, min_row=8, max_row=ultima_riga)

barre = BarChart()
barre.type = "col"
barre.title = "Spese per categoria"
barre.y_axis.title = 'Euro'
barre.add_data(dati_barre, titles_from_data=True)
barre.set_categories(cat_barre)
foglio_analisi.add_chart(barre, "D25")


excel.save(file_path)

"""Funzione che calcola l'andamento della liquidità giorno per giorno"""

#movimento netto giornaliero
movimento_giorno = {}
for riga in estratto_conto.iter_rows(min_row=2, values_only=True):
    data = riga[0]
    importo = riga[1]
    if data in movimento_giorno:
        movimento_giorno[data] += importo
    else:
        movimento_giorno[data] = importo

#ordina dalla data più lontana alla più recente
date_ordinate = sorted(movimento_giorno)

#ordino estratto conto per data
transazioni = list(estratto_conto.iter_rows(min_row=2, values_only=True))
transazioni_ordinate = sorted(transazioni, key=lambda riga: riga[0])

riga_corrente = 2
for riga in transazioni_ordinate:
    for numero_colonna, valore in enumerate(riga, start=1):
        estratto_conto.cell(row=riga_corrente, column=numero_colonna, value=valore)
    riga_corrente += 1

#calcolo saldo progressivo partendo da 0 nel foglio dell'estratto conto
estratto_conto['F1'] = 'Saldo'

saldo = 0
riga_corrente = 2

for riga in estratto_conto.iter_rows(min_row=2, values_only=True):
    saldo  += riga[1]
    estratto_conto[f'F{riga_corrente}'] = saldo
    riga_corrente += 1

excel.save(file_path)


#creazione grafico

from openpyxl.chart import LineChart, Reference

ultima_riga = estratto_conto.max_row

dati = Reference(estratto_conto, min_col=6, min_row=2, max_row=ultima_riga)
date = Reference(estratto_conto, min_col=1, min_row=2, max_row=ultima_riga)

grafico = LineChart()
grafico.type = "line"
grafico.title = "Andamento liquidità"
grafico.y_axis.title = "Euro"

grafico.add_data(dati, titles_from_data=True)
grafico.set_categories(date)

foglio_analisi.add_chart(grafico, "A25")
excel.save(file_path)

"""Sistemazione del layout"""

from openpyxl.styles import Font, PatternFill, Border, Side, Alignment
from openpyxl.utils import range_boundaries
from openpyxl.chart.layout import Layout, ManualLayout

GRIGIO="F2F2F3"; BIANCO="FFFFFF"; NAVY="1F3864"; BORDO="A6A6A6"

#sfondo grigio
fill_grigio = PatternFill("solid", fgColor=GRIGIO)
for r in range(1, 61):
    for c in range(1, 20):
        foglio_analisi.cell(r, c).fill = fill_grigio

#larghezza colonne
foglio_analisi.column_dimensions['A'].width = 26
foglio_analisi.column_dimensions['B'].width = 15

#intestazioni
foglio_analisi['A7'] = "Categoria"; foglio_analisi['B7'] = "Spesa"


sottile = Side(style="thin", color=BORDO)
bordo_box = Border(left=sottile, right=sottile, top=sottile, bottom=sottile)

def carta_bianca(rng):                       # riquadro bianco + bordi
    c1, r1, c2, r2 = range_boundaries(rng)
    for r in range(r1, r2+1):
        for c in range(c1, c2+1):
            cell = foglio_analisi.cell(r, c)
            cell.fill = PatternFill("solid", fgColor=BIANCO)
            cell.border = bordo_box

def header_navy(rng):                         # intestazione navy, testo bianco grande
    c1, r1, c2, r2 = range_boundaries(rng)
    for r in range(r1, r2+1):
        for c in range(c1, c2+1):
            cell = foglio_analisi.cell(r, c)
            cell.fill = PatternFill("solid", fgColor=NAVY)
            cell.font = Font(color="FFFFFF", bold=True, size=12)
            cell.border = bordo_box


# Tabella totali
carta_bianca("A1:B4")
header_navy("A1:A4")
for r in range(1, 5):
    foglio_analisi.cell(r, 2).font = Font(bold=True, size=12, color="1F3864")
    foglio_analisi.cell(r, 2).alignment = Alignment(horizontal="right")

# Tabella categorie
carta_bianca("A7:B15")
header_navy("A7:B7")


# Grafici
foglio_analisi._charts = []                   # svuoto le posizioni originali
for ch in (torta, barre, grafico):
    ch.style = 10
    ch.width = 15
    ch.height = 8

barre.series[0].graphicalProperties.solidFill = NAVY   # barre navy uniformi
linea = grafico.series[0]
linea.graphicalProperties.line.solidFill = NAVY        # linea navy
linea.graphicalProperties.line.width = 22000
linea.smooth = False

foglio_analisi.add_chart(torta,   "D2")
foglio_analisi.add_chart(barre,   "D20")
foglio_analisi.add_chart(grafico, "D38")

#titolo grafico a torta
torta.title.layout = Layout(
    manualLayout=ManualLayout(x=0.0, y=0.0, xMode="edge", yMode="edge")
)

# grafico a barre
from openpyxl.chart.series import DataPoint

colori = ["1F3864", "2E75B6", "5B9BD5", "70AD47",
          "FFC000", "C55A11", "7030A0", "A6A6A6"]

serie = barre.series[0]

for i, col in enumerate(colori):
    punto = DataPoint(idx=i)
    punto.graphicalProperties.solidFill = col
    serie.data_points.append(punto)


# barre.y_axis.title = None # This line caused the error
barre.y_axis.delete = False          # tiene visibile l'asse coi valori
barre.y_axis.majorTickMark = "out"   # tacche rivolte verso l'esterno
barre.y_axis.crosses = 'max'
barre.y_axis.title.layout = Layout(manualLayout=ManualLayout(x=0.0, y=0.4, xMode="edge", yMode="edge"))



# grafico andamento liquidità
grafico.legend = None
grafico.x_axis.delete = False
grafico.y_axis.delete = False
grafico.y_axis.crosses = 'max'
grafico.y_axis.title.layout = Layout(manualLayout=ManualLayout(x=0.0, y=0.4, xMode="edge", yMode="edge"))
grafico.x_axis.majorTickMark = "out"
grafico.y_axis.majorTickMark = "out"


excel.save(file_path)